# 베이스 이미지 선택
FROM python:3.11-slim

# 작업 디렉토리 설정
WORKDIR /app

# Poetry 설치
RUN pip install poetry

# Poetry 가상환경 생성하지 않도록 설정
RUN poetry config virtualenvs.create false

# 의존성 파일 복사
COPY ./pipeline/pyproject.toml ./pipeline/poetry.lock ./

# 의존성 설치
RUN poetry install --no-interaction --no-ansi --no-root

# 소스 코드 복사
COPY ./pipeline .

EXPOSE 8002


CMD ["poetry", "run", "python", "app.py"]
